apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "orders.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
